# Generated by Django 5.2.17 on 2026-09-07 06:49

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("value", models.JSONField(default=dict)),
                ("description", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="FeatureFlag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("enabled", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="AudiencePreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("feature", models.CharField(max_length=64)),
                ("context", models.JSONField(blank=True, default=dict)),
                (
                    "context_hash",
                    models.CharField(blank=True, default="", editable=False, max_length=64),
                ),
                (
                    "value",
                    models.DecimalField(decimal_places=6, default=Decimal("0"), max_digits=9),
                ),
                ("sample_count", models.PositiveIntegerField(default=0)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["feature", "updated_at"], name="ops_audienc_feature_112dd9_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("feature", "context_hash"), name="uniq_pref_feature_ctx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("actor", models.CharField(default="system", max_length=255)),
                ("action", models.CharField(max_length=128)),
                ("entity_type", models.CharField(max_length=128)),
                ("entity_id", models.CharField(max_length=64)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"], name="ops_auditlo_entity__52db88_idx"
                    ),
                    models.Index(
                        fields=["action", "created_at"], name="ops_auditlo_action_f4d18a_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["enabled"], name="ops_topic_enabled_3e577d_idx")],
            },
        ),
        migrations.CreateModel(
            name="Subtopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("1"),
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subtopics",
                        to="ops.topic",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["topic", "enabled"], name="ops_subtopi_topic_i_0fd74b_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("topic", "slug"), name="uniq_subtopic_topic_slug"
                    )
                ],
            },
        ),
    ]
