# Generated by Django 5.2.17 on 2026-09-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="audiencepreference",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="chk_audiencepref_confidence_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="subtopic",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gte", 0)), name="chk_subtopic_weight_ge_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.CheckConstraint(
                condition=models.Q(("weight__gte", 0)), name="chk_topic_weight_ge_0"
            ),
        ),
    ]
