# Generated by Django 5.2.17 on 2026-09-07 06:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EngagementSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("captured_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "post_age_seconds",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("views", models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ("forwards", models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ("shares", models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ("reactions", models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ("replies", models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ("saves", models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ("raw_metrics", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name="SourceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="Platform-native id (message id, post id). Null when unavailable.",
                        max_length=512,
                        null=True,
                    ),
                ),
                ("canonical_url", models.URLField(blank=True, default="", max_length=2048)),
                ("url_hash", models.CharField(blank=True, default="", max_length=64)),
                ("title", models.CharField(blank=True, default="", max_length=1024)),
                ("raw_text", models.TextField(blank=True, default="")),
                ("normalized_text", models.TextField(blank=True, default="")),
                ("content_hash", models.CharField(blank=True, default="", max_length=64)),
                ("media", models.JSONField(blank=True, default=dict)),
                ("language", models.CharField(default="und", max_length=10)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("post", "Post"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("poll", "Poll"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Real publish time at the source, not fetch time.",
                        null=True,
                    ),
                ),
                ("collected_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("collected", "Collected"),
                            ("parsed", "Parsed"),
                            ("analyzed", "Analyzed"),
                            ("ranked", "Ranked"),
                            ("selected", "Selected"),
                            ("content_ready", "Content ready"),
                            ("approved", "Approved"),
                            ("auto_approved", "Auto-approved"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("rejected", "Rejected"),
                        ],
                        default="collected",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="items",
                        to="sources.source",
                    ),
                ),
            ],
        ),
    ]
