# Generated by Django 5.2.17 on 2026-09-07 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0001_initial"),
        ("ops", "0001_initial"),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceitem",
            name="story",
            field=models.ForeignKey(
                blank=True,
                help_text="Primary story cache. Membership table is the rich link.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="sourceitem",
            name="subtopic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ops.subtopic",
            ),
        ),
        migrations.AddField(
            model_name="sourceitem",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="ops.topic",
            ),
        ),
        migrations.AddField(
            model_name="engagementsnapshot",
            name="source_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="news.sourceitem",
            ),
        ),
        migrations.AddIndex(
            model_name="sourceitem",
            index=models.Index(
                fields=["source", "collected_at"], name="news_source_source__20f282_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceitem",
            index=models.Index(
                fields=["status", "collected_at"], name="news_source_status_168ad0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceitem",
            index=models.Index(fields=["published_at"], name="news_source_publish_0188d5_idx"),
        ),
        migrations.AddIndex(
            model_name="sourceitem",
            index=models.Index(fields=["content_hash"], name="news_source_content_0608c8_idx"),
        ),
        migrations.AddIndex(
            model_name="sourceitem",
            index=models.Index(fields=["url_hash"], name="news_source_url_has_255fb6_idx"),
        ),
        migrations.AddConstraint(
            model_name="sourceitem",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="uniq_item_source_external"
            ),
        ),
        migrations.AddIndex(
            model_name="engagementsnapshot",
            index=models.Index(
                fields=["source_item", "post_age_seconds"], name="news_engage_source__658f3f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="engagementsnapshot",
            constraint=models.UniqueConstraint(
                fields=("source_item", "captured_at"), name="uniq_snap_item_captured"
            ),
        ),
    ]
