# Generated by Django 5.2.17 on 2026-09-07 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0002_initial"),
        ("ops", "0002_audiencepreference_chk_audiencepref_confidence_0_1_and_more"),
        ("sources", "0002_source_chk_source_reliability_0_1_and_more"),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceitem",
            name="story",
            field=models.ForeignKey(
                blank=True,
                help_text="Current Story assignment; must match the single current membership.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="stories.story",
            ),
        ),
        migrations.AddIndex(
            model_name="sourceitem",
            index=models.Index(
                fields=["story", "collected_at"], name="news_source_story_i_ae3b4c_idx"
            ),
        ),
    ]
