# Generated by Django 5.2.17 on 2026-09-07 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_sourceitem_story_and_more"),
        ("ops", "0002_audiencepreference_chk_audiencepref_confidence_0_1_and_more"),
        ("sources", "0003_fetchrun"),
        ("stories", "0002_remove_story_stories_sto_status_db3efc_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourceitem",
            name="raw_content_hash",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="sourceitem",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="SHA-256 hash of normalized_text for exact deduplication.",
                max_length=64,
            ),
        ),
        migrations.AddIndex(
            model_name="sourceitem",
            index=models.Index(fields=["raw_content_hash"], name="news_source_raw_con_e2597b_idx"),
        ),
    ]
