# Generated by Django 5.2.17 on 2026-09-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0004_sourceitem_raw_content_hash_and_more"),
        ("ops", "0002_audiencepreference_chk_audiencepref_confidence_0_1_and_more"),
        ("sources", "0004_alter_fetchrun_status"),
        ("stories", "0002_remove_story_stories_sto_status_db3efc_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourceitem",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="SHA-256 hash of normalized_text for exact deduplication. NULL when absent.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourceitem",
            name="raw_content_hash",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="SHA-256 of raw_text. NULL when text is absent.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="sourceitem",
            name="url_hash",
            field=models.CharField(
                blank=True,
                default=None,
                help_text="SHA-256 of canonical_url. NULL when URL is absent so empty URLs never collide.",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceitem",
            constraint=models.UniqueConstraint(
                fields=("source", "url_hash"), name="uniq_item_source_url_hash"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceitem",
            constraint=models.UniqueConstraint(
                fields=("source", "content_hash"), name="uniq_item_source_content_hash"
            ),
        ),
    ]
