# Generated by Django 5.2.17 on 2026-09-08 02:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0005_alter_sourceitem_content_hash_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceItemRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("source_updated_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("observed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("title", models.CharField(blank=True, default="", max_length=1024)),
                ("raw_text", models.TextField(blank=True, default="")),
                ("normalized_text", models.TextField(blank=True, default="")),
                (
                    "content_hash",
                    models.CharField(blank=True, default=None, max_length=64, null=True),
                ),
                ("change_metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["revision_number"],
            },
        ),
        migrations.AddField(
            model_name="engagementsnapshot",
            name="target_age_seconds",
            field=models.PositiveIntegerField(
                blank=True,
                default=None,
                help_text="Scheduled milestone bucket (e.g. 600, 1800, 3600). NULL = ad-hoc/immediate capture, not a milestone.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sourceitem",
            name="source_deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="sourceitem",
            name="source_updated_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddIndex(
            model_name="engagementsnapshot",
            index=models.Index(
                fields=["source_item", "target_age_seconds"], name="news_engage_source__b6c54f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="engagementsnapshot",
            constraint=models.UniqueConstraint(
                fields=("source_item", "target_age_seconds"), name="uniq_snap_item_target_age"
            ),
        ),
        migrations.AddField(
            model_name="sourceitemrevision",
            name="source_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="revisions",
                to="news.sourceitem",
            ),
        ),
        migrations.AddIndex(
            model_name="sourceitemrevision",
            index=models.Index(
                fields=["source_item", "revision_number"], name="news_source_source__2f5a0f_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceitemrevision",
            constraint=models.UniqueConstraint(
                fields=("source_item", "revision_number"), name="uniq_revision_item_number"
            ),
        ),
    ]
