# Generated by Django 5.2.17 on 2026-09-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_sourceitemrevision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="engagementsnapshot",
            name="capture_reason",
            field=models.CharField(
                choices=[
                    ("initial", "Initial ingest observation"),
                    ("milestone", "Scheduled milestone capture"),
                    ("edit_observation", "Re-observation on edit/update"),
                    ("manual", "Manual capture"),
                ],
                default="milestone",
                help_text="Why this snapshot was taken; baseline queries filter on this.",
                max_length=16,
            ),
        ),
    ]
