# Generated by Django 5.2.17 on 2026-09-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0007_engagementsnapshot_capture_reason"),
        ("ops", "0002_audiencepreference_chk_audiencepref_confidence_0_1_and_more"),
        ("sources", "0006_telegramaccountruntimestate"),
        ("stories", "0002_remove_story_stories_sto_status_db3efc_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="sourceitem",
            index=models.Index(
                fields=["language", "published_at"], name="news_source_languag_9e0022_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sourceitem",
            index=models.Index(
                fields=["status", "published_at"], name="news_source_status_9eb9a6_idx"
            ),
        ),
    ]
