# Generated by Django 5.2.17 on 2026-09-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0008_sourceitem_news_source_languag_9e0022_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("original_url", models.URLField(blank=True, default="", max_length=2048)),
                ("platform_media_id", models.CharField(blank=True, default="", max_length=256)),
                ("media_type", models.CharField(default="image", max_length=32)),
                ("mime_type", models.CharField(blank=True, default="", max_length=64)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("aspect_ratio", models.FloatField(blank=True, null=True)),
                ("caption", models.TextField(blank=True, default="")),
                ("position", models.PositiveSmallIntegerField(default=0)),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SHA-256 of media payload or identifier",
                        max_length=64,
                    ),
                ),
                (
                    "provenance",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Adapter, origin platform, source details",
                    ),
                ),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("failure_reason", models.CharField(blank=True, default="", max_length=128)),
                (
                    "telegram_file_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Cached Telegram file_id after successful upload",
                        max_length=256,
                    ),
                ),
                (
                    "source_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_assets",
                        to="news.sourceitem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source_item", "validation_status"],
                        name="news_mediaa_source__d1d608_idx",
                    ),
                    models.Index(
                        fields=["validation_status", "-created_at"],
                        name="news_mediaa_validat_a42a9c_idx",
                    ),
                ],
            },
        ),
    ]
