# Generated by Django 5.2.17 on 2026-09-07 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0001_initial"),
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Story",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("canonical_title", models.CharField(max_length=1024)),
                ("summary", models.TextField(blank=True, default="")),
                ("language", models.CharField(default="und", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("emerging", "Emerging"),
                            ("active", "Active"),
                            ("stale", "Stale"),
                            ("archived", "Archived"),
                        ],
                        default="emerging",
                        max_length=16,
                    ),
                ),
                ("first_published_at", models.DateTimeField(blank=True, null=True)),
                ("first_seen_at", models.DateTimeField(auto_now_add=True)),
                ("latest_update_at", models.DateTimeField(auto_now=True)),
                (
                    "independent_source_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Distinct INDEPENDENT confirmations, not raw item count. Service separates copy-network duplicates from independent confirmation; membership.detail carries the evidence so the model never blocks that.",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Future confirmation breakdown, e.g. copy-networks vs independent.",
                    ),
                ),
                (
                    "primary_subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ops.subtopic",
                    ),
                ),
                (
                    "primary_topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ops.topic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoryMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "similarity_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, default=None, max_digits=5, null=True
                    ),
                ),
                (
                    "match_method",
                    models.CharField(
                        choices=[
                            ("shared_url", "Shared URL"),
                            ("title_sim", "Similar title"),
                            ("content_sim", "Similar content"),
                            ("semantic", "Semantic similarity"),
                            ("shared_entities", "Shared entities"),
                            ("ai_verified", "AI verified"),
                            ("manual", "Manual"),
                        ],
                        default="title_sim",
                        max_length=16,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("detail", models.JSONField(blank=True, default=dict)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="news.sourceitem",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="stories.story",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["status", "-latest_update_at"], name="stories_sto_status_db3efc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["primary_topic", "status"], name="stories_sto_primary_98dd35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["-first_published_at"], name="stories_sto_first_p_6fb666_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storymembership",
            index=models.Index(
                fields=["story", "is_primary"], name="stories_sto_story_i_e1d610_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storymembership",
            index=models.Index(fields=["source_item"], name="stories_sto_source__a663c0_idx"),
        ),
        migrations.AddConstraint(
            model_name="storymembership",
            constraint=models.UniqueConstraint(
                fields=("story", "source_item"), name="uniq_membership_story_item"
            ),
        ),
    ]
