# Generated by Django 5.2.17 on 2026-09-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_alter_sourceitem_story_and_more"),
        ("ops", "0002_audiencepreference_chk_audiencepref_confidence_0_1_and_more"),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="story",
            name="stories_sto_status_db3efc_idx",
        ),
        migrations.RemoveField(
            model_name="story",
            name="latest_update_at",
        ),
        migrations.AddField(
            model_name="story",
            name="latest_source_update_at",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Time of last material source update attached to this story. Maintained by services, not auto_now, so ranking freshness is truthful.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="storymembership",
            name="current_slot",
            field=models.PositiveBigIntegerField(
                default=0, editable=False, help_text="source_item id when is_current, else 0."
            ),
        ),
        migrations.AddField(
            model_name="storymembership",
            name="is_current",
            field=models.BooleanField(
                default=True,
                help_text="Only one membership per SourceItem may be current (active assignment).",
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["status", "-latest_source_update_at"], name="stories_sto_status_9a4b4d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="story",
            index=models.Index(
                fields=["-latest_source_update_at"], name="stories_sto_latest__884a0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storymembership",
            index=models.Index(
                fields=["story", "is_current"], name="stories_sto_story_i_4099cd_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="storymembership",
            constraint=models.UniqueConstraint(
                fields=("current_slot",), name="uniq_membership_current_per_item"
            ),
        ),
    ]
