# Generated by Django 5.2.17 on 2026-09-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0008_sourceitem_news_source_languag_9e0022_idx_and_more"),
        ("stories", "0002_remove_story_stories_sto_status_db3efc_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClusteringDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("match", "Match to existing story"),
                            ("new_story", "Create new story"),
                            ("ambiguous", "Ambiguous, needs review/AI judge"),
                            ("reassign", "Reassign item to another story"),
                            ("merge", "Merge two stories"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "match_score",
                    models.DecimalField(
                        blank=True, decimal_places=4, default=None, max_digits=5, null=True
                    ),
                ),
                ("feature_snapshot", models.JSONField(blank=True, default=dict)),
                ("algorithm_version", models.CharField(max_length=32)),
                ("threshold_version", models.CharField(blank=True, default="", max_length=32)),
                ("embedding_model", models.CharField(blank=True, default="", max_length=128)),
                ("embedding_version", models.CharField(blank=True, default="", max_length=64)),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. lexical/semantic/evidence.",
                        max_length=32,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "content_hash",
                    models.CharField(
                        help_text="SourceItem.content_hash at embed time; mismatch means STALE.",
                        max_length=64,
                    ),
                ),
                ("provider", models.CharField(default="fastembed", max_length=32)),
                ("model", models.CharField(max_length=128)),
                ("model_version", models.CharField(default="", max_length=64)),
                ("dimension", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("indexed", "Indexed"),
                            ("failed", "Failed"),
                            ("stale", "Stale"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "point_id",
                    models.CharField(
                        help_text="Deterministic Qdrant point id (item pk based).",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ItemMinHash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("num_perm", models.PositiveIntegerField()),
                ("scheme", models.CharField(default="affine32", max_length=16)),
                ("digest", models.JSONField(help_text="List of uint32 digest values.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name="story",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                help_text="Target story after merge. Set only when status is MERGED.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="merged_stories",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="observed_source_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Distinct configured sources with current membership. Raw count.",
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="primary_item",
            field=models.ForeignKey(
                blank=True,
                help_text="Deterministic representative member (earliest reliable publication).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="news.sourceitem",
            ),
        ),
        migrations.AddField(
            model_name="storymembership",
            name="independence",
            field=models.CharField(
                choices=[
                    ("independent", "Independent"),
                    ("likely_copy", "Likely copy/syndication"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="storymembership",
            name="independence_score",
            field=models.DecimalField(
                blank=True,
                decimal_places=4,
                default=None,
                help_text="0..1 confidence that this member is an independent confirmation.",
                max_digits=5,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="status",
            field=models.CharField(
                choices=[
                    ("emerging", "Emerging"),
                    ("active", "Active"),
                    ("stale", "Stale"),
                    ("archived", "Archived"),
                    ("merged", "Merged"),
                ],
                default="emerging",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="storymembership",
            index=models.Index(
                fields=["story", "independence"], name="stories_sto_story_i_ef6de1_idx"
            ),
        ),
        migrations.AddField(
            model_name="clusteringdecision",
            name="candidate_story",
            field=models.ForeignKey(
                blank=True,
                help_text="Best candidate considered. NULL when no candidate existed.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="clustering_decisions",
                to="stories.story",
            ),
        ),
        migrations.AddField(
            model_name="clusteringdecision",
            name="source_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clustering_decisions",
                to="news.sourceitem",
            ),
        ),
        migrations.AddField(
            model_name="itemembedding",
            name="source_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_embedding",
                to="news.sourceitem",
            ),
        ),
        migrations.AddField(
            model_name="itemminhash",
            name="source_item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_minhash",
                to="news.sourceitem",
            ),
        ),
        migrations.AddIndex(
            model_name="clusteringdecision",
            index=models.Index(
                fields=["source_item", "-created_at"], name="stories_clu_source__576240_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clusteringdecision",
            index=models.Index(
                fields=["candidate_story", "-created_at"], name="stories_clu_candida_7252b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clusteringdecision",
            index=models.Index(
                fields=["algorithm_version", "decision", "-created_at"],
                name="stories_clu_algorit_a2fa7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="itemembedding",
            index=models.Index(
                fields=["status", "updated_at"], name="stories_ite_status_38f9ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="itemembedding",
            index=models.Index(
                fields=["model", "model_version"], name="stories_ite_model_c5f017_idx"
            ),
        ),
    ]
