# Generated by Django 5.2.17 on 2026-09-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0008_sourceitem_news_source_languag_9e0022_idx_and_more"),
        ("stories", "0003_clusteringdecision_itemembedding_itemminhash_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clusteringdecision",
            name="relationship",
            field=models.CharField(
                blank=True,
                choices=[
                    ("same_event", "Same event"),
                    ("material_update", "Material update of the event"),
                    ("related_event", "Related but distinct event"),
                    ("unrelated", "Unrelated"),
                ],
                default="",
                help_text="Inter-story relationship label, reserved for Phase 5+ classifiers.",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="clusteringdecision",
            index=models.Index(
                fields=["relationship", "-created_at"], name="stories_clu_relatio_d9e213_idx"
            ),
        ),
    ]
