# Generated by Django 5.2.17 on 2026-09-19 08:44

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stories", "0004_clusteringdecision_relationship_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoryMomentumSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "captured_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("watching", "Watching"),
                            ("rising", "Rising"),
                            ("breaking", "Breaking"),
                            ("peaking", "Peaking"),
                            ("cooling", "Cooling"),
                            ("stale", "Stale"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "trend_state",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("early_signal", "Early Signal"),
                            ("rising", "Rising"),
                            ("surging", "Surging"),
                            ("breaking", "Breaking"),
                            ("saturated", "Saturated"),
                            ("cooling", "Cooling"),
                        ],
                        db_index=True,
                        max_length=24,
                    ),
                ),
                (
                    "previous_lifecycle_state",
                    models.CharField(blank=True, default="", max_length=24),
                ),
                ("transition_reason", models.CharField(blank=True, default="", max_length=128)),
                ("view_velocity", models.FloatField(blank=True, null=True)),
                ("forward_velocity", models.FloatField(blank=True, null=True)),
                ("share_velocity", models.FloatField(blank=True, null=True)),
                ("reaction_velocity", models.FloatField(blank=True, null=True)),
                ("reply_velocity", models.FloatField(blank=True, null=True)),
                ("engagement_velocity", models.FloatField(blank=True, null=True)),
                ("normalized_velocity", models.FloatField(blank=True, null=True)),
                ("ewma_velocity", models.FloatField(blank=True, null=True)),
                ("acceleration", models.FloatField(blank=True, null=True)),
                ("source_arrival_5m", models.PositiveSmallIntegerField(default=0)),
                ("source_arrival_15m", models.PositiveSmallIntegerField(default=0)),
                ("source_arrival_30m", models.PositiveSmallIntegerField(default=0)),
                ("independent_arrival_15m", models.PositiveSmallIntegerField(default=0)),
                ("independent_arrival_30m", models.PositiveSmallIntegerField(default=0)),
                ("observed_sources_count", models.PositiveIntegerField(default=0)),
                ("independent_sources_count", models.PositiveIntegerField(default=0)),
                ("source_diversity", models.FloatField(blank=True, null=True)),
                ("platform_diversity", models.FloatField(blank=True, null=True)),
                ("propagation_breadth", models.FloatField(blank=True, null=True)),
                ("propagation_depth", models.FloatField(blank=True, null=True)),
                ("freshness_score", models.FloatField(blank=True, null=True)),
                ("trend_age_seconds", models.PositiveIntegerField(default=0)),
                ("growth_consistency", models.FloatField(blank=True, null=True)),
                ("growth_persistence", models.PositiveSmallIntegerField(default=0)),
                ("burst_factor", models.FloatField(blank=True, null=True)),
                ("time_to_double_seconds", models.FloatField(blank=True, null=True)),
                (
                    "momentum_score",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=5),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=5),
                ),
                ("component_breakdown", models.JSONField(blank=True, default=dict)),
                ("transition_metrics", models.JSONField(blank=True, default=dict)),
                ("algorithm_version", models.CharField(default="momentum-v1", max_length=32)),
                (
                    "idempotency_hash",
                    models.CharField(blank=True, default=None, max_length=64, null=True),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="momentum_snapshots",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["story", "-captured_at"], name="stories_sto_story_i_55d77d_idx"
                    ),
                    models.Index(
                        fields=["lifecycle_state", "-captured_at"],
                        name="stories_sto_lifecyc_497ad1_idx",
                    ),
                    models.Index(
                        fields=["trend_state", "-captured_at"],
                        name="stories_sto_trend_s_7891a4_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("story", "idempotency_hash"), name="uniq_momentum_story_idemp"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryObservationState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lifecycle_state",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("watching", "Watching"),
                            ("rising", "Rising"),
                            ("breaking", "Breaking"),
                            ("peaking", "Peaking"),
                            ("cooling", "Cooling"),
                            ("stale", "Stale"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="discovered",
                        max_length=24,
                    ),
                ),
                (
                    "trend_state",
                    models.CharField(
                        choices=[
                            ("normal", "Normal"),
                            ("early_signal", "Early Signal"),
                            ("rising", "Rising"),
                            ("surging", "Surging"),
                            ("breaking", "Breaking"),
                            ("saturated", "Saturated"),
                            ("cooling", "Cooling"),
                        ],
                        db_index=True,
                        default="normal",
                        max_length=24,
                    ),
                ),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("sample_count", models.PositiveIntegerField(default=0)),
                ("last_observed_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "next_observation_at",
                    models.DateTimeField(blank=True, db_index=True, default=None, null=True),
                ),
                ("observation_interval_seconds", models.PositiveIntegerField(default=300)),
                (
                    "latest_momentum",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=5),
                ),
                (
                    "latest_confidence",
                    models.DecimalField(decimal_places=4, default=Decimal("0.0000"), max_digits=5),
                ),
                ("last_fast_path_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("algorithm_version", models.CharField(default="momentum-v1", max_length=32)),
                (
                    "story",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observation_state",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["active", "next_observation_at"],
                        name="stories_sto_active_5aacf8_idx",
                    ),
                    models.Index(
                        fields=["lifecycle_state", "latest_momentum"],
                        name="stories_sto_lifecyc_b71495_idx",
                    ),
                    models.Index(
                        fields=["trend_state", "next_observation_at"],
                        name="stories_sto_trend_s_837c6c_idx",
                    ),
                ],
            },
        ),
    ]
