# Generated by Django 5.2.17 on 2026-09-07 06:49

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("twitter_x", "Twitter/X"),
                            ("rss", "RSS/Atom"),
                            ("rsshub", "RSSHub"),
                            ("website_html", "Website (static HTML)"),
                            ("website_dynamic", "Website (JS-rendered)"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "identifier",
                    models.CharField(
                        help_text="Canonical handle per platform: @channel, feed URL, site domain.",
                        max_length=512,
                    ),
                ),
                ("url", models.URLField(blank=True, default="", max_length=2048)),
                ("enabled", models.BooleanField(default=True)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                (
                    "reliability_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.5"),
                        help_text="0..1. Historical accuracy.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "trust_score",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.5"),
                        help_text="0..1. Ranking input, updated by ops.",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("language", models.CharField(default="und", max_length=10)),
                ("fetch_interval_seconds", models.PositiveIntegerField(default=300)),
                (
                    "configuration",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Per-source adapter settings only. Never secrets.",
                    ),
                ),
                ("last_success_at", models.DateTimeField(blank=True, null=True)),
                ("last_failure_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["platform", "enabled"], name="sources_sou_platfor_8ac1c6_idx"
                    ),
                    models.Index(
                        fields=["enabled", "priority"], name="sources_sou_enabled_c2883a_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "identifier"), name="uniq_source_platform_identifier"
                    )
                ],
            },
        ),
    ]
