# Generated by Django 5.2.17 on 2026-09-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(("reliability_score__gte", 0), ("reliability_score__lte", 1)),
                name="chk_source_reliability_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(("trust_score__gte", 0), ("trust_score__lte", 1)),
                name="chk_source_trust_0_1",
            ),
        ),
    ]
