# Generated by Django 5.2.17 on 2026-09-07 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0002_source_chk_source_reliability_0_1_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FetchRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("not_modified", "Not modified (304)"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("http_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("fetched_count", models.PositiveIntegerField(default=0)),
                ("created_count", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("rejected_count", models.PositiveIntegerField(default=0)),
                ("error_type", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("correlation_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fetch_runs",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "-started_at"], name="sources_fet_source__cc3529_idx"
                    ),
                    models.Index(
                        fields=["status", "-started_at"], name="sources_fet_status_95107a_idx"
                    ),
                ],
            },
        ),
    ]
