# Generated by Django 5.2.17 on 2026-09-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0003_fetchrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fetchrun",
            name="status",
            field=models.CharField(
                choices=[
                    ("running", "Running"),
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("not_modified", "Not modified (304)"),
                ],
                default="running",
                max_length=16,
            ),
        ),
    ]
