# Generated by Django 5.2.17 on 2026-09-08 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0006_sourceitemrevision_and_more"),
        ("sources", "0004_alter_fetchrun_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="fetchrun",
            name="updated_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="source",
            name="cooldown_until",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="source",
            name="platform_external_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.CreateModel(
            name="EngagementTrackingState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "next_due_at",
                    models.DateTimeField(blank=True, db_index=True, default=None, null=True),
                ),
                (
                    "next_target_age_seconds",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("active", models.BooleanField(default=True)),
                ("last_attempt_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("failure_count", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="engagement_tracking",
                        to="news.sourceitem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["active", "next_due_at"], name="sources_eng_active_8de0b5_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceCheckpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("adapter", models.CharField(default="telegram", max_length=32)),
                (
                    "last_external_id",
                    models.CharField(blank=True, default=None, max_length=512, null=True),
                ),
                ("last_published_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "state",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Adapter-scoped cursor state, e.g. {'last_message_id': 1234}. Never secrets. Small and JSON-serializable.",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkpoints",
                        to="sources.source",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "adapter"], name="sources_sou_source__1cfd67_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "adapter"), name="uniq_checkpoint_source_adapter"
                    )
                ],
            },
        ),
    ]
