# Generated by Django 5.2.17 on 2026-09-08 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sources", "0005_fetchrun_updated_count_source_cooldown_until_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramAccountRuntimeState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("account_key", models.CharField(max_length=64, unique=True)),
                ("cooldown_until", models.DateTimeField(blank=True, default=None, null=True)),
                ("last_error_type", models.CharField(blank=True, default="", max_length=64)),
                ("last_error_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["account_key"], name="sources_tel_account_3ac548_idx")
                ],
            },
        ),
    ]
