# Generated by Django 5.2.17 on 2026-09-07 06:49

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import apps.ranking.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ops", "0001_initial"),
        ("publishing", "0001_initial"),
        ("sources", "0001_initial"),
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RankingWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64, unique=True)),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("enabled", models.BooleanField(default=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["enabled"], name="ranking_ran_enabled_352aac_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="DecisionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "algorithm_version",
                    models.CharField(
                        max_length=32, validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
                (
                    "decision_type",
                    models.CharField(
                        choices=[
                            ("what", "What (publish or skip)"),
                            ("when", "When (timing)"),
                            ("how", "How (template/style)"),
                        ],
                        max_length=8,
                    ),
                ),
                ("feature_snapshot", models.JSONField(default=dict)),
                ("score_breakdown", models.JSONField(blank=True, default=dict)),
                (
                    "predicted_reward",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                ("selected_action", models.CharField(max_length=64)),
                ("action_detail", models.JSONField(blank=True, default=dict)),
                ("is_exploration", models.BooleanField(default=False)),
                (
                    "exploration_probability",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "actual_reward",
                    models.DecimalField(
                        blank=True, decimal_places=6, default=None, max_digits=9, null=True
                    ),
                ),
                ("reward_calculated_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "publication",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="decisions",
                        to="publishing.publication",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decisions",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["story", "decision_type", "-created_at"],
                        name="ranking_dec_story_i_3eb630_idx",
                    ),
                    models.Index(
                        fields=["algorithm_version", "decision_type", "-created_at"],
                        name="ranking_dec_algorit_6f0feb_idx",
                    ),
                    models.Index(
                        fields=["publication", "decision_type"],
                        name="ranking_dec_publica_aefd5a_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoreRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "algorithm_version",
                    models.CharField(
                        max_length=32, validators=[django.core.validators.MinLengthValidator(1)]
                    ),
                ),
                (
                    "news_value",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "audience_fit",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "momentum",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "final_score",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "breakdown",
                    models.JSONField(
                        default=dict,
                        help_text="{news_value: {...}, audience_fit: {...}, momentum: {...}}",
                        validators=[apps.ranking.models.validate_breakdown],
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scores",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["story", "-created_at"], name="ranking_sco_story_i_02dcc8_idx"
                    ),
                    models.Index(
                        fields=["algorithm_version", "-final_score"],
                        name="ranking_sco_algorit_f2b93b_idx",
                    ),
                    models.Index(
                        fields=["-final_score", "-created_at"],
                        name="ranking_sco_final_s_2570b6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceBaseline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("telegram", "Telegram"),
                            ("twitter_x", "Twitter/X"),
                            ("rss", "RSS/Atom"),
                            ("rsshub", "RSSHub"),
                            ("website_html", "Website (static HTML)"),
                            ("website_dynamic", "Website (JS-rendered)"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("article", "Article"),
                            ("post", "Post"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("poll", "Poll"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "age_bucket_minutes",
                    models.PositiveIntegerField(
                        help_text="Snapshot schedule bucket, e.g. 10, 30, 60, 180, 360, 720, 1440."
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("views", "Views"),
                            ("forwards", "Forwards"),
                            ("shares", "Shares"),
                            ("reactions", "Reactions"),
                            ("replies", "Replies"),
                            ("saves", "Saves"),
                        ],
                        max_length=16,
                    ),
                ),
                ("context_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("sample_count", models.PositiveIntegerField(default=0)),
                ("p25", models.FloatField(blank=True, default=None, null=True)),
                ("p50", models.FloatField(blank=True, default=None, null=True)),
                ("p75", models.FloatField(blank=True, default=None, null=True)),
                ("p90", models.FloatField(blank=True, default=None, null=True)),
                ("p95", models.FloatField(blank=True, default=None, null=True)),
                ("p99", models.FloatField(blank=True, default=None, null=True)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("1")),
                        ],
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null = platform-level fallback baseline.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="baselines",
                        to="sources.source",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ops.subtopic",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="ops.topic",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["source", "metric", "age_bucket_minutes"],
                        name="idx_baseline_lookup",
                    ),
                    models.Index(
                        fields=["platform", "metric"], name="ranking_sou_platfor_9bd579_idx"
                    ),
                ],
            },
        ),
    ]
