# Generated by Django 5.2.17 on 2026-09-07 09:11

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ops", "0002_audiencepreference_chk_audiencepref_confidence_0_1_and_more"),
        ("publishing", "0002_alter_publication_content_hash"),
        ("ranking", "0001_initial"),
        ("sources", "0002_source_chk_source_reliability_0_1_and_more"),
        ("stories", "0002_remove_story_stories_sto_status_db3efc_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sourcebaseline",
            name="metric",
            field=models.CharField(max_length=32),
        ),
        migrations.AddConstraint(
            model_name="decisionlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_exploration", False),
                    models.Q(
                        ("exploration_probability__gte", 0), ("exploration_probability__lte", 1)
                    ),
                    _connector="OR",
                ),
                name="chk_decision_expl_prob_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="decisionlog",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("predicted_reward__isnull", True),
                    models.Q(("predicted_reward__gte", 0), ("predicted_reward__lte", 1)),
                    _connector="OR",
                ),
                name="chk_decision_predicted_reward_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="rankingweight",
            constraint=models.CheckConstraint(
                condition=models.Q(("value__gte", Decimal("0")), ("value__lte", Decimal("1"))),
                name="chk_rankingweight_value_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("news_value__gte", 0), ("news_value__lte", 1)),
                name="chk_scorerecord_news_value_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("audience_fit__gte", 0), ("audience_fit__lte", 1)),
                name="chk_scorerecord_audience_fit_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("momentum__gte", 0), ("momentum__lte", 1)),
                name="chk_scorerecord_momentum_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(("final_score__gte", 0), ("final_score__lte", 1)),
                name="chk_scorerecord_final_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourcebaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(("confidence__gte", 0), ("confidence__lte", 1)),
                name="chk_baseline_confidence_0_1",
            ),
        ),
    ]
