# Generated by Django 5.2.17 on 2026-09-19 08:44

from decimal import Decimal

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0003_publication_delivery_metadata_and_more"),
        ("ranking", "0002_alter_sourcebaseline_metric_and_more"),
        ("stories", "0005_storymomentumsnapshot_storyobservationstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicationSelectionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("run_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("algorithm_version", models.CharField(default="ranking-v1", max_length=32)),
                ("policy_version", models.CharField(default="editorial-v1", max_length=32)),
                (
                    "candidates",
                    models.JSONField(
                        default=list,
                        help_text="List of evaluated candidate stories with features, scores, rank, and outcome",
                    ),
                ),
                ("selected_count", models.PositiveSmallIntegerField(default=0)),
                ("summary", models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="decision_batch_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="policy_version",
            field=models.CharField(blank=True, default="editorial-v1", max_length=32),
        ),
        migrations.AddField(
            model_name="decisionlog",
            name="reward_breakdown",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Decomposed reward: views, forwards, reactions, replies",
            ),
        ),
        migrations.AddField(
            model_name="scorerecord",
            name="newsworthiness_score",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="scorerecord",
            name="publish_priority_score",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("0.0000"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("1")),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="decisionlog",
            name="decision_type",
            field=models.CharField(
                choices=[
                    ("what", "What (publish or skip)"),
                    ("when", "When (timing)"),
                    ("how", "How (template/style)"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="decisionlog",
            index=models.Index(fields=["decision_batch_id"], name="ranking_dec_decisio_b78271_idx"),
        ),
        migrations.AddConstraint(
            model_name="scorerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("newsworthiness_score__gte", 0), ("newsworthiness_score__lte", 1)
                ),
                name="chk_scorerecord_newsworthiness_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="scorerecord",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("publish_priority_score__gte", 0), ("publish_priority_score__lte", 1)
                ),
                name="chk_scorerecord_publish_priority_0_1",
            ),
        ),
        migrations.AddIndex(
            model_name="publicationselectionrun",
            index=models.Index(fields=["-run_at"], name="ranking_pub_run_at_83f1f6_idx"),
        ),
    ]
