# Generated by Django 5.2.17 on 2026-09-07 06:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "channel",
                    models.CharField(
                        help_text="Destination, e.g. @channel or channel id.", max_length=255
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("approved", "Approved"),
                            ("scheduled", "Scheduled"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("publication_version", models.PositiveIntegerField(default=1)),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("initial", "Initial publish"),
                            ("material_update", "Material update"),
                            ("correction", "Correction"),
                        ],
                        default="initial",
                        max_length=16,
                    ),
                ),
                ("headline", models.CharField(blank=True, default="", max_length=1024)),
                ("content", models.TextField(blank=True, default="")),
                (
                    "content_hash",
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text="SHA-256 of rendered content, filled pre-save. NULL while draft has no content yet; NULLs stay distinct under UNIQUE so empty drafts never collide.",
                        max_length=64,
                        null=True,
                    ),
                ),
                ("template_version", models.CharField(blank=True, default="", max_length=32)),
                ("headline_style", models.CharField(blank=True, default="", max_length=32)),
                ("tone", models.CharField(blank=True, default="", max_length=32)),
                (
                    "emoji_level",
                    models.PositiveSmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "technical_depth",
                    models.PositiveSmallIntegerField(blank=True, default=None, null=True),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("published_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("external_message_id", models.CharField(blank=True, default="", max_length=128)),
                (
                    "idempotency_key",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[django.core.validators.MinLengthValidator(1)],
                    ),
                ),
                ("last_error", models.TextField(blank=True, default="")),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="publications",
                        to="stories.story",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PublicationEngagementSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("captured_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post_age_seconds",
                    models.PositiveIntegerField(blank=True, default=None, null=True),
                ),
                ("views", models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ("forwards", models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ("reactions", models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ("replies", models.PositiveBigIntegerField(blank=True, default=None, null=True)),
                ("raw_metrics", models.JSONField(blank=True, default=dict)),
                (
                    "publication",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="publishing.publication",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["status", "scheduled_at"], name="publishing__status_bb7e81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(fields=["story", "channel"], name="publishing__story_i_f36295_idx"),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["channel", "-published_at"], name="publishing__channel_238b74_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="publication",
            index=models.Index(
                fields=["status", "-created_at"], name="publishing__status_55ad12_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                fields=("story", "channel", "publication_version"),
                name="uniq_pub_story_channel_version",
            ),
        ),
        migrations.AddConstraint(
            model_name="publication",
            constraint=models.UniqueConstraint(
                fields=("story", "channel", "content_hash"), name="uniq_pub_story_channel_content"
            ),
        ),
        migrations.AddIndex(
            model_name="publicationengagementsnapshot",
            index=models.Index(
                fields=["publication", "post_age_seconds"], name="publishing__publica_5bd0aa_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="publicationengagementsnapshot",
            constraint=models.UniqueConstraint(
                fields=("publication", "captured_at"), name="uniq_pub_snap_pub_captured"
            ),
        ),
    ]
