# Generated by Django 5.2.17 on 2026-09-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publishing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="content_hash",
            field=models.CharField(
                blank=True,
                default=None,
                editable=False,
                help_text="SHA-256 of final rendered payload, recomputed on every save. NULL while draft has no visible content; NULLs stay distinct under UNIQUE.",
                max_length=64,
                null=True,
            ),
        ),
    ]
