# Generated by Django 5.2.17 on 2026-09-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0009_mediaasset"),
        ("publishing", "0002_alter_publication_content_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="delivery_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Media dispatch status, fallback rationale, and provider responses",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="editorial_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Headline candidates, review scores, and editorial rationale",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="fingerprint_version",
            field=models.CharField(blank=True, default="fp-v1", max_length=32),
        ),
        migrations.AddField(
            model_name="publication",
            name="parent_publication",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="follow_ups",
                to="publishing.publication",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="selected_media",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="publications",
                to="news.mediaasset",
            ),
        ),
        migrations.AddField(
            model_name="publication",
            name="telegram_chat_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="publication",
            name="telegram_message_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="publication",
            name="update_sequence",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
