# Generated by Django 6.0.8 on 2026-09-08 21:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("news", "0008_sourceitem_news_source_languag_9e0022_idx_and_more"),
        ("ops", "0002_audiencepreference_chk_audiencepref_confidence_0_1_and_more"),
        ("stories", "0004_clusteringdecision_relationship_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AICallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(db_index=True, max_length=32)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("task", models.CharField(db_index=True, max_length=32)),
                ("prompt_version", models.CharField(blank=True, default="", max_length=32)),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveIntegerField(default=0)),
                ("output_tokens", models.PositiveIntegerField(default=0)),
                ("cached", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("cached", "Cached"),
                            ("failure", "Failure"),
                            ("timeout", "Timeout"),
                            ("invalid_response", "Invalid Response"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("error_type", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["task", "-created_at"], name="ai_aicalllo_task_36b619_idx"
                    ),
                    models.Index(
                        fields=["status", "-created_at"], name="ai_aicalllo_status_06548a_idx"
                    ),
                    models.Index(
                        fields=["provider", "model"], name="ai_aicalllo_provide_13660b_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIResultCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("task", models.CharField(db_index=True, max_length=32)),
                ("prompt_version", models.CharField(blank=True, default="", max_length=32)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                ("payload", models.JSONField(default=dict)),
                ("algorithm_version", models.CharField(default="ai-v1", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("expires_at", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["input_hash"], name="ai_airesult_input_h_d1a0c5_idx"),
                    models.Index(fields=["expires_at"], name="ai_airesult_expires_064a15_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "prompt_version", "model", "input_hash"),
                        name="uniq_ai_cache_task_prompt_model_input",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("has_conflict", models.BooleanField(default=False)),
                ("summary", models.TextField(blank=True, default="")),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("provider", models.CharField(default="fake", max_length=32)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("prompt_version", models.CharField(blank=True, default="", max_length=32)),
                ("algorithm_version", models.CharField(default="ai-v1", max_length=32)),
                (
                    "story",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflict",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TopicClassification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("candidate_topic", models.CharField(blank=True, default="", max_length=128)),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                ("provider", models.CharField(default="fake", max_length=32)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("prompt_version", models.CharField(blank=True, default="", max_length=32)),
                ("algorithm_version", models.CharField(default="ai-v1", max_length=32)),
                (
                    "story",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topic_classification",
                        to="stories.story",
                    ),
                ),
                (
                    "subtopic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ops.subtopic",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="ops.topic",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AITask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task",
                    models.CharField(
                        help_text="e.g. topic_classification, news_value, conflict_detection, clustering_judge, material_update_detection, post_draft.",
                        max_length=32,
                    ),
                ),
                ("provider", models.CharField(default="fake", max_length=32)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("prompt_version", models.CharField(blank=True, default="", max_length=32)),
                ("input_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error_type", models.CharField(blank=True, default="", max_length=64)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("last_attempt_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_tasks",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["story", "task"], name="ai_aitask_story_i_b3590d_idx"),
                    models.Index(fields=["state", "created_at"], name="ai_aitask_state_ec4351_idx"),
                    models.Index(fields=["task", "state"], name="ai_aitask_task_f7b4aa_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="ClusteringJudgeDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="SAME_EVENT, MATERIAL_UPDATE, RELATED_BUT_DISTINCT, UNRELATED.",
                        max_length=24,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("applied", models.BooleanField(default=False)),
                ("provider", models.CharField(default="fake", max_length=32)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("prompt_version", models.CharField(blank=True, default="", max_length=32)),
                ("algorithm_version", models.CharField(default="ai-v1", max_length=32)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "candidate_story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_judge_decisions",
                        to="stories.story",
                    ),
                ),
                (
                    "decision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_judge_decisions",
                        to="stories.clusteringdecision",
                    ),
                ),
                (
                    "source_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_judge_decisions",
                        to="news.sourceitem",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["candidate_story", "-created_at"],
                        name="ai_clusteri_candida_316b11_idx",
                    ),
                    models.Index(
                        fields=["label", "-created_at"], name="ai_clusteri_label_ad5837_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MaterialUpdateDecision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "label",
                    models.CharField(
                        help_text="NO_NEW_INFORMATION, MINOR_UPDATE, MATERIAL_UPDATE, CORRECTION, MAJOR_BREAKING_UPDATE.",
                        max_length=24,
                    ),
                ),
                (
                    "confidence",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("provider", models.CharField(default="fake", max_length=32)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("prompt_version", models.CharField(blank=True, default="", max_length=32)),
                ("algorithm_version", models.CharField(default="ai-v1", max_length=32)),
                ("reason_codes", models.JSONField(blank=True, default=list)),
                (
                    "source_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_update_decisions",
                        to="news.sourceitem",
                    ),
                ),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_updates",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["story", "-created_at"], name="ai_material_story_i_c61bd8_idx"
                    ),
                    models.Index(
                        fields=["label", "-created_at"], name="ai_material_label_f411e8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="StoryNewsValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "importance",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "utility",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "impact",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "novelty",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "urgency",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "credibility",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                ("component_detail", models.JSONField(blank=True, default=dict)),
                ("provider", models.CharField(default="fake", max_length=32)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("prompt_version", models.CharField(blank=True, default="", max_length=32)),
                ("algorithm_version", models.CharField(default="ai-v1", max_length=32)),
                (
                    "story",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news_value",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["algorithm_version"], name="ai_storynew_algorit_1495a3_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("importance__gte", 0),
                            ("importance__lte", 1),
                            ("utility__gte", 0),
                            ("utility__lte", 1),
                            ("impact__gte", 0),
                            ("impact__lte", 1),
                            ("novelty__gte", 0),
                            ("novelty__lte", 1),
                            ("urgency__gte", 0),
                            ("urgency__lte", 1),
                            ("credibility__gte", 0),
                            ("credibility__lte", 1),
                        ),
                        name="chk_newsvalue_components_0_1",
                    )
                ],
            },
        ),
    ]
