# Generated by Django 5.2.17 on 2026-09-19 08:44

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
        ("stories", "0005_storymomentumsnapshot_storyobservationstate"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialupdatedecision",
            name="information_unit_diff",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Fact-level diff: new, changed, repeated, and contradicted claims.",
            ),
        ),
        migrations.CreateModel(
            name="StoryIntelligenceSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("evidence_hash", models.CharField(db_index=True, max_length=64)),
                ("canonical_event", models.TextField(blank=True, default="")),
                ("what_happened", models.TextField(blank=True, default="")),
                ("who", models.JSONField(blank=True, default=list)),
                ("where", models.JSONField(blank=True, default=list)),
                ("when", models.CharField(blank=True, default="", max_length=255)),
                ("why_it_matters", models.TextField(blank=True, default="")),
                ("confirmed_facts", models.JSONField(blank=True, default=list)),
                ("uncertain_claims", models.JSONField(blank=True, default=list)),
                ("conflicting_claims", models.JSONField(blank=True, default=list)),
                ("new_information", models.JSONField(blank=True, default=list)),
                ("missing_information", models.JSONField(blank=True, default=list)),
                (
                    "importance",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.5000"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "impact",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.5000"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "utility",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.5000"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "novelty",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.5000"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "urgency",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.5000"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "credibility",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.5000"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "editorial_risk",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("0.0000"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1),
                        ],
                    ),
                ),
                (
                    "recommended_depth",
                    models.CharField(blank=True, default="standard", max_length=32),
                ),
                (
                    "recommended_tone",
                    models.CharField(blank=True, default="neutral", max_length=32),
                ),
                ("reasoning_summary", models.CharField(blank=True, default="", max_length=500)),
                ("provider", models.CharField(default="fake", max_length=32)),
                ("model", models.CharField(blank=True, default="", max_length=128)),
                ("prompt_version", models.CharField(blank=True, default="v2", max_length=32)),
                ("task_version", models.CharField(default="intel-v2", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "story",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="intelligence_snapshots",
                        to="stories.story",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["story", "-created_at"], name="ai_storyint_story_i_3e741a_idx"
                    ),
                    models.Index(fields=["evidence_hash"], name="ai_storyint_evidenc_0459bb_idx"),
                ],
            },
        ),
    ]
