class DomainError(Exception): ...


class SourceUnavailableError(DomainError): ...


class AuthenticationExpiredError(DomainError): ...


class AIProviderError(DomainError): ...


class PublishingError(DomainError): ...


class RateLimitError(DomainError): ...


class ParsingError(DomainError): ...
